# Generated by Django 3.0.8 on 2020-10-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthday',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='birthday',
            name='lname',
        ),
        migrations.AddField(
            model_name='birthday',
            name='email',
            field=models.EmailField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='birthday',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='zipcode',
            field=models.CharField(max_length=20),
        ),
    ]
