# Generated by Django 3.0.8 on 2020-10-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_user1'),
    ]

    operations = [
        migrations.CreateModel(
            name='greduation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('address', models.CharField(default='', max_length=70)),
                ('address2', models.CharField(default='', max_length=500)),
                ('city', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank='True', upload_to='shop/display/')),
            ],
        ),
        migrations.CreateModel(
            name='weds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('address', models.CharField(default='', max_length=70)),
                ('address2', models.CharField(default='', max_length=500)),
                ('city', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.DeleteModel(
            name='User1',
        ),
        migrations.RemoveField(
            model_name='birthday',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='birthday',
            name='address2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='address',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='city',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='email',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
