# Generated by Django 3.0.8 on 2020-10-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20201021_1511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Birthday',
            new_name='birthday1',
        ),
    ]
