# Generated by Django 3.0.8 on 2020-10-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20201021_1639'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='birthday1',
            new_name='birth',
        ),
    ]
