# Generated by Django 3.0.8 on 2020-10-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_user1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User1',
        ),
    ]
